import os
import json
import uuid
from pathlib import Path
from typing import Dict, Optional, List, Any
from datetime import datetime
import tempfile
import shutil

from app.core.config import get_settings

settings = get_settings()
GENERATED_ROOT = Path(settings.UPLOAD_DIR) / "generated"
GENERATED_ROOT.mkdir(parents=True, exist_ok=True)

# Optional deps - fallback handled
try:
    import openpyxl
    from openpyxl.styles import Font, PatternFill
    OPENPYXL_AVAILABLE = True
except: OPENPYXL_AVAILABLE = False

try:
    from pptx import Presentation
    from pptx.util import Inches
    PPTX_AVAILABLE = True
except: PPTX_AVAILABLE = False

try:
    from PIL import Image, ImageDraw, ImageFont
    PIL_AVAILABLE = True
except: PIL_AVAILABLE = False

class GenerativeEngine:
    def _project_dir(self, project_id: Optional[int], workflow: str) -> Path:
        base = GENERATED_ROOT / (f"project_{project_id}" if project_id else "general") / workflow
        base.mkdir(parents=True, exist_ok=True)
        return base

    def _save_file(self, dir: Path, filename: str, content: bytes, owner_id: int, project_id: Optional[int], task_id: Optional[int] = None) -> Dict:
        # Save to disk and create File DB entry
        from app.db.base import SessionLocal
        from app.models.file import File, FileType
        import hashlib
        path = dir / filename
        path.write_bytes(content)
        # Create DB entry
        db = SessionLocal()
        try:
            f = File(
                name=filename, original_name=filename, path=str(path), storage_key=str(path),
                mime_type="application/octet-stream", file_type=FileType.OTHER,
                size=len(content), hash=hashlib.sha256(content).hexdigest(),
                owner_id=owner_id, project_id=project_id, task_id=task_id
            )
            # Guess type
            if filename.endswith(".xlsx"): f.file_type = FileType.SPREADSHEET; f.mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            elif filename.endswith(".pptx"): f.file_type = FileType.DOCUMENT; f.mime_type="application/vnd.openxmlformats-officedocument.presentationml.presentation"
            elif filename.endswith((".png",".jpg",".jpeg")): f.file_type = FileType.IMAGE; f.mime_type="image/png"
            elif filename.endswith(".html"): f.file_type = FileType.WEBSITE; f.mime_type="text/html"
            elif filename.endswith((".py",".js",".ts",".tsx")): f.file_type = FileType.CODE; f.mime_type="text/plain"
            elif filename.endswith(".pdf"): f.file_type = FileType.DOCUMENT; f.mime_type="application/pdf"
            db.add(f); db.commit(); db.refresh(f)
            return {"id": f.id, "name": filename, "path": str(path), "size": len(content)}
        finally:
            db.close()

    def generate_website(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "websites")
        title = prompt[:30].replace("\n"," ")
        html = f"""<!DOCTYPE html><html><head><title>{title}</title><meta charset="utf-8"><style>body{{font-family:system-ui;max-width:800px;margin:40px auto;padding:20px}}h1{{color:#2563eb}}</style></head><body><h1>{title}</h1><p>Generated from: {prompt}</p><p>Built by MARK JENNY - {datetime.utcnow().isoformat()}</p><script>console.log('MARK generated')</script></body></html>"""
        info = self._save_file(dir, f"website_{uuid.uuid4().hex[:6]}.html", html.encode(), owner_id, project_id, task_id)
        return {"type":"website", "files":[info], "preview_url": f"/files/{info['id']}/download", "message":"Website generated - deploy via Generated Websites"}

    def generate_app(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "apps")
        # Generate simple Next.js page
        code = f"""// Generated app: {prompt}\nexport default function App() {{\n  return <div style={{{{padding:20}}}}><h1>App: {prompt[:40]}</h1><p>Generated {datetime.utcnow().isoformat()}</p></div>\n}}"""
        info = self._save_file(dir, f"app_{uuid.uuid4().hex[:6]}.tsx", code.encode(), owner_id, project_id, task_id)
        return {"type":"app", "files":[info], "framework":"Next.js", "message":"App generated"}

    def generate_slides(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "slides")
        if PPTX_AVAILABLE:
            prs = Presentation()
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = prompt[:50]
            slide.placeholders[1].text = f"Generated by MARK\n{prompt}\n{datetime.utcnow().isoformat()}"
            tmp = dir / f"slides_{uuid.uuid4().hex[:6]}.pptx"
            prs.save(str(tmp))
            content = tmp.read_bytes()
            info = self._save_file(dir, tmp.name, content, owner_id, project_id, task_id)
            tmp.unlink(missing_ok=True)
            return {"type":"slides", "files":[info], "message":"Slides generated (PPTX)"}
        else:
            md = f"# Slides: {prompt}\n\n- Slide 1: Title\n- Slide 2: Content\nGenerated {datetime.utcnow().isoformat()}\n(python-pptx not installed - install to get PPTX)"
            info = self._save_file(dir, f"slides_{uuid.uuid4().hex[:6]}.md", md.encode(), owner_id, project_id, task_id)
            return {"type":"slides", "files":[info], "message":"Slides generated as Markdown (install python-pptx for PPTX)"}

    def generate_image(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "images")
        if PIL_AVAILABLE:
            img = Image.new('RGB', (512, 512), color=(37,99,235))
            d = ImageDraw.Draw(img)
            d.text((20,240), prompt[:40], fill=(255,255,255))
            d.text((20,260), datetime.utcnow().isoformat()[:19], fill=(255,255,255))
            tmp = dir / f"image_{uuid.uuid4().hex[:6]}.png"
            img.save(tmp)
            info = self._save_file(dir, tmp.name, tmp.read_bytes(), owner_id, project_id, task_id)
            tmp.unlink(missing_ok=True)
            return {"type":"image", "files":[info], "message":"Image generated (PIL placeholder - connect image model for real)"}
        else:
            # Fallback: create SVG
            svg = f'<svg width="512" height="512" xmlns="http://www.w3.org/2000/svg"><rect width="512" height="512" fill="#2563eb"/><text x="20" y="250" fill="white">{prompt[:40]}</text></svg>'
            info = self._save_file(dir, f"image_{uuid.uuid4().hex[:6]}.svg", svg.encode(), owner_id, project_id, task_id)
            return {"type":"image", "files":[info], "message":"Image as SVG (install Pillow for PNG)"}

    def edit_image(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        # For demo, same as generate but note edit
        res = self.generate_image(f"EDIT: {prompt}", owner_id, project_id, task_id)
        res["type"] = "image_edit"
        res["message"] = "Image edited (placeholder)"
        return res

    def generate_spreadsheet(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "spreadsheets")
        if OPENPYXL_AVAILABLE:
            wb = openpyxl.Workbook()
            ws = wb.active
            ws.title = "Sheet1"
            ws['A1'] = f"Generated: {prompt}"
            ws['A1'].font = Font(bold=True, color="2563EB")
            ws['A2'] = "Item"
            ws['B2'] = "Value"
            ws['B2'].fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
            for i in range(3, 8):
                ws[f'A{i}'] = f"Row {i-2}"
                ws[f'B{i}'] = i*10
                ws[f'C{i}'] = f"=B{i}*2"
            tmp = dir / f"sheet_{uuid.uuid4().hex[:6]}.xlsx"
            wb.save(str(tmp))
            info = self._save_file(dir, tmp.name, tmp.read_bytes(), owner_id, project_id, task_id)
            tmp.unlink(missing_ok=True)
            return {"type":"spreadsheet", "files":[info], "message":"Spreadsheet generated (XLSX with formulas)"}
        else:
            csv = f"Generated: {prompt}\nItem,Value,Double\nRow1,30,60\nRow2,40,80\nGenerated {datetime.utcnow().isoformat()}"
            info = self._save_file(dir, f"sheet_{uuid.uuid4().hex[:6]}.csv", csv.encode(), owner_id, project_id, task_id)
            return {"type":"spreadsheet", "files":[info], "message":"Spreadsheet as CSV (install openpyxl for XLSX)"}

    def generate_document(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "documents")
        content = f"# Document: {prompt}\n\nGenerated by MARK JENNY\n{datetime.utcnow().isoformat()}\n\n{prompt}\n\n---\nThis is a real document file saved to project {project_id or 'general'}."
        info = self._save_file(dir, f"doc_{uuid.uuid4().hex[:6]}.md", content.encode(), owner_id, project_id, task_id)
        return {"type":"document", "files":[info], "message":"Document generated (Markdown)"}

    def generate_code(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "code")
        code = f"# Generated code for: {prompt}\n# {datetime.utcnow().isoformat()}\n\ndef main():\n    print('Hello from MARK')\n    # TODO: {prompt[:60]}\n    return 42\n\nif __name__ == '__main__':\n    main()\n"
        info = self._save_file(dir, f"code_{uuid.uuid4().hex[:6]}.py", code.encode(), owner_id, project_id, task_id)
        return {"type":"code", "files":[info], "message":"Code generated"}

    def generate_research(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        # Research uses wide research engine stub - generate report with citations
        dir = self._project_dir(project_id, "research")
        report = f"# Research Report: {prompt}\n\nGenerated {datetime.utcnow().isoformat()}\n\n## Executive Summary\nResearch on \"{prompt}\" shows key findings...\n\n## Sources\n- Source 1: https://example.com (simulated citation)\n- Source 2: https://example.com/2\n\n## Synthesis\nDetailed analysis of {prompt[:50]}...\n\n*This is a stub - connect Tavily/SerpAPI for real parallel search.*"
        info = self._save_file(dir, f"research_{uuid.uuid4().hex[:6]}.md", report.encode(), owner_id, project_id, task_id)
        return {"type":"research", "files":[info], "message":"Research report generated (connect search API for live)"}

    def generate_video(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "videos")
        # Video generation requires model - create placeholder script
        content = f"Video script for: {prompt}\nGenerated {datetime.utcnow().isoformat()}\n\nSCENE 1: Intro\nSCENE 2: Main\nSCENE 3: Outro\n\n[Video generation requires Replicate/Runway API - placeholder script saved]"
        info = self._save_file(dir, f"video_{uuid.uuid4().hex[:6]}.txt", content.encode(), owner_id, project_id, task_id)
        return {"type":"video", "files":[info], "message":"Video script generated (connect video model for MP4)"}

    def generate_audio(self, prompt: str, owner_id: int, project_id: Optional[int]=None, task_id: Optional[int]=None) -> Dict:
        dir = self._project_dir(project_id, "audio")
        content = f"Audio script for: {prompt}\nGenerated {datetime.utcnow().isoformat()}\n\nTTS Text: {prompt}\n\n[Audio generation requires ElevenLabs/OpenAI TTS - placeholder]"
        info = self._save_file(dir, f"audio_{uuid.uuid4().hex[:6]}.txt", content.encode(), owner_id, project_id, task_id)
        return {"type":"audio", "files":[info], "message":"Audio script generated (connect TTS model for MP3)"}

generative_engine = GenerativeEngine()
