from fastapi import APIRouter
from app.api.v1.endpoints import auth, users, projects, tasks, files, schedules, websocket, project_workspace, chat, quick_actions, knowledge, memory, skills, browser, computer, execution, models, generative, settings, admin, advanced, advanced_features, agent_brain, agents, integrations, extensions, features, self_build, advanced_intelligence, advanced_workflows, voice, cybersecurity_agent

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(projects.router, prefix="/projects", tags=["projects"])
api_router.include_router(tasks.router, prefix="/tasks", tags=["tasks"])
api_router.include_router(files.router, prefix="/files", tags=["files"])
api_router.include_router(schedules.router, prefix="/schedules", tags=["schedules"])
api_router.include_router(websocket.router, prefix="/ws", tags=["websocket"])
api_router.include_router(project_workspace.router, prefix="", tags=["project-workspace"])
api_router.include_router(chat.router, prefix="/chats", tags=["chats"])
api_router.include_router(quick_actions.router, prefix="/quick-actions", tags=["quick-actions"])
api_router.include_router(knowledge.router, prefix="/knowledge", tags=["knowledge"])
api_router.include_router(memory.router, prefix="/memories", tags=["memories"])
api_router.include_router(skills.router, prefix="/skills", tags=["skills"])
api_router.include_router(browser.router, prefix="/browser", tags=["browser"])
api_router.include_router(computer.router, prefix="/computer", tags=["computer"])
api_router.include_router(execution.router, prefix="/execution", tags=["execution"])
api_router.include_router(models.router, prefix="/ai", tags=["ai"])
api_router.include_router(generative.router, prefix="/generate", tags=["generate"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(advanced.router, prefix="/advanced", tags=["advanced"])
api_router.include_router(advanced_features.router, prefix="/advanced", tags=["advanced"])
api_router.include_router(agent_brain.router, prefix="/agent-brain", tags=["agent-brain"])
api_router.include_router(agents.router, prefix="/agents", tags=["agents"])
api_router.include_router(integrations.router, prefix="/integrations", tags=["integrations"])
api_router.include_router(extensions.router, prefix="/extensions", tags=["extensions"])
api_router.include_router(features.router, prefix="/features", tags=["features"])
api_router.include_router(self_build.router, prefix="/self-build", tags=["self-build"])
api_router.include_router(advanced_intelligence.router, prefix="/intelligence", tags=["advanced-intelligence"])
api_router.include_router(advanced_workflows.router, prefix="/workflows", tags=["advanced-workflows"])
api_router.include_router(voice.router, prefix="/voice", tags=["voice"])
api_router.include_router(cybersecurity_agent.router, prefix="/cybersecurity-agent", tags=["cybersecurity-agent"])