# Generated by Mark-Imti
# Create database schema and migrations
# Request: Create a simple hello world web page
Build target: web
Sandbox mode: web
# AI model unavailable — manual implementation required
